'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Incursion.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Incursion_Main_Theme_Test1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Incursion_Main_Theme_Test1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0;Short-sword;3;3;1;1.1;100;A short iron sword, well forged and sturdy, with an unadorned guard and pommel. The grip is simple leather.
        '''0;Dagger;1;2;1;0.2;25;A small iron dagger, well forged and sturdy, with an unadorned guard and pommel. The grip is simple leather.
        '''0;Elegant Short-sword;6;6;1;1.2;235;A short steel sword of impeccable forging. The guard is engraved and the pommel is banded with gold leaf. The grip is fine quality leather, ensuring a tighter hold.
        '''0;Elegant Dagger;2;3;1;0.3;75;A small ste [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Items() As String
            Get
                Return ResourceManager.GetString("Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MeetingWithAGod() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MeetingWithAGod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0/0/ ;
        '''0/7/ ;
        '''0/8/ ;
        '''14/6/%;
        '''14/8/_;
        '''15/11/↑;
        '''15/4/↓;
        '''1/9/≈;
        '''6/14/░;
        '''10/10/ ;
        '''9/11/▒;
        '''8/7/⌂;
        '''2/10/♣;
        '''6/15/▒;
        '''9/10/│;
        '''9/10/─;
        '''9/10/┤;
        '''9/10/├;
        '''9/10/┴;
        '''9/10/┬;
        '''9/10/┼;
        '''9/10/┐;
        '''9/10/└;
        '''9/10/┌;
        '''9/10/┘;
        '''8/7/▲;
        '''15/8/¶;
        '''15/7/¡;.
        '''</summary>
        Friend ReadOnly Property Terrain() As String
            Get
                Return ResourceManager.GetString("Terrain", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
